// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD08_zAnHXeamdXZQ7aGSxAWN6n1T13gk8',
    appId: '1:917016400830:web:abc6372ffb26a19cd79fef',
    messagingSenderId: '917016400830',
    projectId: 'internproject-af1ca',
    authDomain: 'internproject-af1ca.firebaseapp.com',
    storageBucket: 'internproject-af1ca.firebasestorage.app',
    measurementId: 'G-28T76B7QG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpEYEJ50qbA-5xQKKE7_LQL-p9AcceUTU',
    appId: '1:917016400830:android:dad501fe9498b98ad79fef',
    messagingSenderId: '917016400830',
    projectId: 'internproject-af1ca',
    storageBucket: 'internproject-af1ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7VfNqgIo9ktdX63MHV3ECheo0ZFXHkE',
    appId: '1:917016400830:ios:d7dfdf026caf796bd79fef',
    messagingSenderId: '917016400830',
    projectId: 'internproject-af1ca',
    storageBucket: 'internproject-af1ca.firebasestorage.app',
    iosBundleId: 'com.example.internFilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI7VfNqgIo9ktdX63MHV3ECheo0ZFXHkE',
    appId: '1:917016400830:ios:d7dfdf026caf796bd79fef',
    messagingSenderId: '917016400830',
    projectId: 'internproject-af1ca',
    storageBucket: 'internproject-af1ca.firebasestorage.app',
    iosBundleId: 'com.example.internFilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD08_zAnHXeamdXZQ7aGSxAWN6n1T13gk8',
    appId: '1:917016400830:web:e9e5bb3eccb63b03d79fef',
    messagingSenderId: '917016400830',
    projectId: 'internproject-af1ca',
    authDomain: 'internproject-af1ca.firebaseapp.com',
    storageBucket: 'internproject-af1ca.firebasestorage.app',
    measurementId: 'G-6QV8Q65LY5',
  );
}
